name: ResClasses
version: 4.7.1
date: 18/12/2017
description: |
    Set-Theoretic Computations with Residue Classes

authors:
    - name: Stefan Kohl
      url: https://stefan-kohl.github.io/

maintainers:
    - name: Stefan Kohl
      url: https://stefan-kohl.github.io/

GAP: ">=4.8.7"

needed-pkgs:
    - name: "GAPDoc"
      version: ">=1.5.1"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "Polycyclic"
      version: ">=2.11"
      url: "http://www.icm.tu-bs.de/ag_algebra/software/polycyclic/"
    - name: "utils"
      version: ">=0.40"
      url: "https://gap-packages.github.io/utils"

suggested-pkgs:
    - name: "IO"
      version: ">=4.4.5"
      url: "https://gap-packages.github.io/io"

www: https://stefan-kohl.github.io/resclasses.html
readme: README.resclasses
packageinfo: https://stefan-kohl.github.io/resclasses/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://stefan-kohl.github.io/resclasses/resclasses-4.7.1.tar.gz

abstract: |
    This package permits to compute with set-theoretic unions of residue classes of&nbsp;Z and a few other rings. In particular it provides methods for computing unions, intersections and differences of these sets.

status: deposited
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
