name: ResClasses
version: "4.7.4"
license: "GPL-2.0-or-later"
date: 2025-09-24
description: |
    Set-Theoretic Computations with Residue Classes

authors:
    - name: Stefan Kohl
      url: https://stefan-kohl.github.io/

maintainers:
    - name: Stefan Kohl
      url: https://stefan-kohl.github.io/

GAP: ">=4.11.1"

needed-pkgs:
    - name: "GAPDoc"
      version: ">=1.5.1"
      url: "https://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "Polycyclic"
      version: ">=2.11"
      url: "https://gap-packages.github.io/polycyclic/"
    - name: "utils"
      version: ">=0.40"
      url: "https://gap-packages.github.io/utils"

suggested-pkgs:
    - name: "IO"
      version: ">=4.4.5"
      url: "https://gap-packages.github.io/io"

www: https://gap-packages.github.io/resclasses/
readme: README
packageinfo: https://gap-packages.github.io/resclasses/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/resclasses/releases/download/v4.7.4/resclasses-4.7.4.tar.gz

abstract: |
    This package permits to compute with set-theoretic unions of residue classes of&nbsp;Z and a few other rings. In particular it provides methods for computing unions, intersections and differences of these sets.

status: deposited
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
keywords: |
    residue classes, integers, number theory.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Koh25</span>]   <b class='BibAuthor'>Kohl, S.</b>,
     <i class='BibTitle'>ResClasses, Set-Theoretic Computations with Residue Classes,
             Version 4.7.4</i>
     (<span class='BibYear'>2025</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/resclasses/">https://gap-packages.github.io/resclasses/</a></span>.
    </p>
    

bibtex: |
    @misc{ ResClasses,
      author =           {Kohl, S.},
      title =            {{ResClasses},        {Set\texttt{\symbol{45}}Theoretic
                          Computations with Residue Classes}, {V}ersion 4.7.4},
      month =            {Sep},
      year =             {2025},
      note =             {GAP package},
      howpublished =     {\href     {https://gap-packages.github.io/resclasses/}
                          {\texttt{https://gap\texttt{\symbol{45}}packages.github.io/}\discretionary
                          {}{}{}\texttt{resclasses/}}},
      keywords =         {residue classes; integers; number theory},
      printedkey =       {Koh25}
    }

